"""Initial Migration

Revision ID: 93669dd1c20f
Revises: 53af5c445bfb
Create Date: 2020-10-01 00:24:21.901777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93669dd1c20f'
down_revision = '53af5c445bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cases_description'), 'cases', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_description'), table_name='cases')
    # ### end Alembic commands ###
